import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#353534",
        "on-secondary": "#233143",
        "surface-variant": "#353534",
        error: "#ffb4ab",
        surface: "#131313",
        tertiary: "#ffb596",
        "surface-container-lowest": "#0e0e0e",
        background: "#131313",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#360f00",
        "secondary-fixed-dim": "#b9c8de",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#c1c6d7",
        "outline-variant": "#414754",
        primary: "#aec6ff",
        "surface-dim": "#131313",
        "secondary-container": "#39485a",
        "on-primary": "#002e6b",
        "on-error": "#690005",
        "on-background": "#e5e2e1",
        outline: "#8b90a0",
        "on-tertiary-container": "#fffeff",
        "inverse-on-surface": "#313030",
        "surface-tint": "#aec6ff",
        "on-tertiary": "#581e00",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#0d1c2d",
        "surface-container-high": "#2a2a2a",
        "on-primary-container": "#ffffff",
        "on-surface": "#e5e2e1",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed": "#d4e4fa",
        "tertiary-fixed-dim": "#ffb596",
        "inverse-primary": "#0059c5",
        "on-primary-fixed-variant": "#004397",
        secondary: "#b9c8de",
        "surface-bright": "#3a3939",
        "on-primary-fixed": "#001a43",
        "tertiary-container": "#ca4e00",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary-fixed-variant": "#39485a",
        "on-tertiary-fixed-variant": "#7d2d00",
        "primary-fixed-dim": "#aec6ff",
        "surface-container": "#201f1f",
        "on-secondary-container": "#a7b6cc",
        "primary-container": "#0070f3",
        "surface-container-low": "#1c1b1b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      boxShadow: {
        glass: "0 40px 40px -10px rgba(0,112,243,0.08)",
        "electric-glow": "0 0 20px rgba(0,112,243,0.35)",
      },
      letterSpacing: {
        tightest: "-0.02em",
      },
      backdropBlur: {
        glass: "24px",
        dock: "30px",
      },
    },
  },
  plugins: [],
};

export default config;
